### ISSUE TITLE
Missing dimension sliders for certain axes information in certain file

### ISSUE THREAD

**Issue by downiec** [CDAT/jupyter-vcdat#101]
**Describe the bug**
When selection to edit the axes information of a particular variable, sometimes an axes is missing (no dimension slider shows up in the modal).

**To Reproduce**
1. Using file: ESACCI-SOILMOISTURE-L3S-SSMV-COMBINED-19790103000000-fv04.4.nc
2. Double click to load variables from file
3. Choose a variable and click the red 'Axes' button.
4. You'll see that only latitude axes is shown, the others are missing.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome

**Comment by doutriaux1** [comment]
@downiec didnt we fix this already? or is it pending?

**Comment by downiec** [comment]
Yeah we fixed this, but it's pending in the branch that Lina is working on (with the selenium tests).
