### ISSUE TITLE
export plot does not store provenance anymore

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/jupyter-vcdat#107]
**Describe the bug**
saving plot with provenance checked generates regular plot w/o provenance.

jupyter code injected is:
```python
canvas.png("demo")
```

**Comment by downiec** [comment]
Can you share the steps needed to install/run command to view the provenance in a png? Then I can start testing and incorporate the bug fix in my next PR.

**Comment by downiec** [comment]
I realize the code injection itself is the issue, but it would be helpful for future reference.

**Comment by downiec** [comment]
@doutriaux1 I'm trying to reproduce the error, but I don't see it. Whenever I toggle capture to 'on' I get the provenance in the command: canvas.png('test', width=814, height=606, units='pixels', provenance=True)

**Comment by doutriaux1** [comment]
@downiec I do not specify a size. Can you try to with "just" provenance and no "custom size"

**Comment by downiec** [comment]
I was able to reproduce the error after some more tests and I think I've fixed it. It'll be in my latest PR.
