### ISSUE TITLE
Closing a notebook will cause an error popup

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/jupyter-vcdat#129]
**Describe the bug**
closing a notebook will cause the message "ERROR: this.layout is null" to pop up.

**To Reproduce**
1. Open a variable, plot someting
2. Close the notebook
3. See error

**Expected behavior**
There should be no errors when closing a notebook

**Screenshots**
<img width="1415" alt="Screen Shot 2019-06-13 at 11 42 09 AM" src="https://user-images.githubusercontent.com/6477639/59459010-a146da80-8dd0-11e9-8cdf-306f2721ab19.png">

**Desktop (please complete the following information):**
 - OS: running on NERSC
 - Browser: Firefox

**Comment by downiec** [comment]
I'm having difficulty reproducing this error. I tried the following:
Open a clt.nc file (wait for load)
Select variable 'clt'
Plot variable
Close notebook

Each time I tried I couldn't get the error to popup.

**Comment by sterlingbaldwin** [comment]
I think it might actually have been a jupyter issue, since I dont think we mess with the layout at all. I'll try it with the new juypter 1.0 and see if its still a problem.

**Comment by downiec** [comment]
Yeah that might be it, I've been trying to reproduce it with Jupyterlab 1.0

**Comment by downiec** [comment]
I will close this issue and we can reopen it if it ever surfaces again.
