### ISSUE TITLE
connecting instruction not working

### ISSUE THREAD

**Issue by chengzhuzhang** [CDAT/jupyter-vcdat#130]
**Describe the bug**
I get
``` 
Spawn failed: Server at http://128.55.224.44:57478/user/chengzhu/cori-shared-node-cpu/ didn't respond in 300 seconds
```
by putting 
```
exec env XDG_RUNTIME_DIR=/tmp/ shifter --volume=$(pwd):/home/jovyan --image=cdoutrix/vcdat:latest -- jupyter-labhub "$@"" in ".override Jupyter"
```
Using 
```
exec /global/common/software/uvcdat/miniconda3/envs/jupyter-vcdat/bin/jupyter-labhub "$@
```
fixed the problem.

**Comment by doutriaux1** [comment]
@chengzhuzhang I talked to NERSC guys who luckily are sitting behing me today. We updated the instructions at: https://github.com/CDAT/jupyter-vcdat/wiki/Connecting#using-vcdat-on-your-machine-or-a-local-network please try this new way.

**Comment by doutriaux1** [comment]
@chengzhuzhang does it work for you now?

**Comment by chengzhuzhang** [comment]
It works for me. @sterlingbaldwin has also tested and it worked.
