### ISSUE TITLE
Variable loading UI lag

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/jupyter-vcdat#133]
**Describe the bug**
After selecting a variable to load, the loading code is injected, and all the info in the varLoader modal is wiped clear, but the modal doesnt actually close until the loading cell completes. This process can take several-to-many seconds depending on the size of the data, and since the varLoader is wiped clean there's no reason for it to continue to be displayed. 

**To Reproduce**
1. Click "load variable"
2. Click on a variable
3. Click "load"
4. Wait around for the loading to complete with an empty modal.

**Expected behavior**
The modal should close once the loading starts, not after it finishes.

**Screenshots**
<img width="1680" alt="Screen Shot 2019-07-11 at 1 16 57 PM" src="https://user-images.githubusercontent.com/6477639/61082371-3348ff80-a3de-11e9-8116-5f14dec39ca2.png">

**Comment by doutriaux1** [comment]
we should
1- not clean until ready to close
2- add a little spinning wheel that says "loading" or something like that.

**Comment by sterlingbaldwin** [comment]
That sounds good. We can copy the code that William used for the PNG saving loader wheel.
