### ISSUE TITLE
First plot throws VCS error, and doesnt plot the correct lon/lat values

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/jupyter-vcdat#137]
When I hit plot in a fresh notebook for the first time I get the following image/output:
![Screen Shot 2019-08-30 at 9 26 50 AM](https://user-images.githubusercontent.com/6477639/64036626-7d11b480-cb08-11e9-908f-3a62f65ba321.png)

Then, when I do nothing but hit the plot button again, it works fine:
![Screen Shot 2019-08-30 at 9 27 01 AM](https://user-images.githubusercontent.com/6477639/64036653-8ac73a00-cb08-11e9-8d8f-7b5340ffb54c.png)

I believe this is an issue with VCS throwing up the error about the incorrect canvas size. Maybe we can query the canvas size and explicitly set it at the init time, or suppress the warning somehow.

**Comment by downiec** [comment]
I've been trying to duplicate this issue but haven't seen it come up. Could you let me know if this is still happening for you and how you are running into it? If this is no longer an issue I'd like to close it.

**Comment by sterlingbaldwin** [comment]
I think this may have been an issue with one of the VCS dependencies, since it seems to work fine with the new version. Im going to close this since its not happening any more on the new VCS version.

**Comment by downiec** [comment]
I'm glad the issue isn't showing up anymore, thanks for closing!
