### ISSUE TITLE
opening from file path not recognizing correct path

### ISSUE THREAD

**Issue by sterlingbaldwin** [CDAT/jupyter-vcdat#153]
**Describe the bug**
When I try and open a file via the "open from path" option, sometimes when the path is correct, and the permissions are fine, it will tell me it cant open it.

**To Reproduce**
1) Go to aims2.llnl.gov/jupyterhub and login
2) select the vCDAT server option
3) Click the vCDAT button on the left
4) paste in the path /p/user_pub/work/CMIP6/CMIP/E3SM-Project/E3SM-1-0/historical/r1i1p1f1/Amon/o3/gr/v20191220/o3_Amon_E3SM-1-0_historical_r1i1p1f1_gr_185001-187412.nc 
5) get an error saying "The path entered is not valid. Make sure it contains an appropriate filename."

As you can see from the screenshot below, I have permissions to read both the directory the file is in, and the file itself, so this isnt a permissions issue.
![Screen Shot 2020-01-07 at 12 01 06 PM](https://user-images.githubusercontent.com/6477639/71925237-7560bd00-3145-11ea-8ac0-27ad08b08cd5.png)

Here is the error I see when I try and open from the file
![Screen Shot 2020-01-07 at 11 58 36 AM](https://user-images.githubusercontent.com/6477639/71925271-83aed900-3145-11ea-9a23-f253588bc18f.png)

**Comment by downiec** [comment]
I'll look into it, thanks!

**Comment by downiec** [comment]
I tried using that path several times and trying different things to see if I could duplicate the issue  but it seems to be working for me every time.

**Comment by sterlingbaldwin** [comment]
ooooh kay. I deleted all the saved paths, and pasted it in, and it worked. No idea why it was failing before and is magically working now. Im going to close this since I guess this isnt a real issue?

**Comment by downiec** [comment]
It could have been an artifact from a previous version? In the last PR that was merged, I had a few changes that were directly meant to fix some bugs/issues I had seen during my testing related to the file path feature.
