### ISSUE TITLE
Creating jupyter-vcdat environment with conda 4.6.x is broken

### ISSUE THREAD

**Issue by William-Hill** [CDAT/jupyter-vcdat#16]
Running the installation instructions for jupyter-vcdat leads to the following error:

`Collecting package metadata: \ WARNING conda.core.index:push_record(193): Skipping cdat/label/nightly/osx-64::libcdms-3.0.2018.06.12.15.57.ga415a0b-0 due to InvalidSpec: >1.10.*
done
Solving environment: failed

InvalidVersionSpec: Invalid version '>1.10.*': invalid operator with '.*'`

This error has been observed when running manually as well as in CircleCI (https://circleci.com/gh/CDAT/jupyter-vcdat/347?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

It seems to be a known issue with conda 4.6 (https://github.com/conda-forge/ipywidgets-feedstock/issues/51)

**Comment by doutriaux1** [comment]
@William-Hill I think this is related to the new conda, try downgrading conda.
```
conda install -n base -f 'conda<4.6'
```
