### ISSUE TITLE
Export plots to local file system

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/jupyter-vcdat#97]
**Describe the solution you'd like**
Rather than saving the image on the server , most of the time the user wants to save it to its local disk for further use in a presentation, etc... 
Adding a toggle to decide where to save the file (locally/remote) would be awesome.

**Comment by doutriaux1** [comment]
For 2.0 we will just document (with pix) how to save it to your local drive. And come back to this after users feedback.

**Comment by sterlingbaldwin** [comment]
I think this is out of scope for the project. This is a built in feature that all web browsers support, we dont need to reinvent every wheel.
