### ISSUE TITLE
can't subset dimension to only ONE value

### ISSUE THREAD

**Issue by doutriaux1** [CDAT/jupyter-vcdat#98]
**Describe the bug**
When using sliders to subset a dimension users cannot select only ONE value.

**To Reproduce**
Click Edit on a variable, try to select only one value from a dimension
**Expected behavior**
Being able to select (0,0) not just (0,1)

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser Chrome/Firefox
 - Version All

**Environment Information**
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda list`</code></summary><p>

```

```
</p></details>

**Additional context**

**Comment by downiec** [comment]
Fixed the bug! The fix will be part of my latest PR once I release.
